import type { Species } from "../types/game";
import { MAX_HEARTS, riskClass } from "../lib/game";

export function JournalScreen({ species, discovered, completed, rank, rankIcon, rankProgress, hearts, onHome }: { species: Species[]; discovered: string[]; completed: string[]; rank: string; rankIcon: string; rankProgress: number; hearts: number; onHome: () => void }) {
return <section className="content notebook-page"><div className="section-heading"><div><span className="eyebrow">היומן האישי שלך</span><h1>יומן השדה</h1><p>כאן נשמרים הרמזים, ההישגים והמינים שכבר פגשת.</p></div><button className="ghost" onClick={onHome}>חזרה למחנה</button></div><div className="journal-grid"><article className="journal-card"><span>דרגה נוכחית</span><strong>{rankIcon} {rank}</strong><p>עוד {100 - rankProgress} XP עד להתקדמות הבאה.</p></article><article className="journal-card"><span>זיהויים שהושלמו</span><strong>{completed.length}</strong><p>כל משימה מוסיפה רמזים חדשים למחברת.</p></article><article className="journal-card"><span>לבבות זמינים</span><strong>{"♥".repeat(hearts)}{"♡".repeat(MAX_HEARTS - hearts)}</strong><p>לב אחד מתחדש בסיום משימה.</p></article></div><div className="journal-list">{species.map((item, index) => { const unlocked = discovered.includes(item.id); return <article key={item.id} className={`journal-entry ${unlocked ? "" : "locked"}`}><div className="page-number">{String(index + 1).padStart(2, "0")}</div><div><span className="handwritten">{unlocked ? "זוהה ביומן" : "טרם נצפה"}</span><h2>{unlocked ? item.name : "מין מסתורי"}</h2><p>{unlocked ? item.identificationClues[0] : "השלימו עוד משלחות כדי לפתוח את העמוד."}</p></div><b>{unlocked ? "✓" : "?"}</b></article>; })}</div></section>;
}

export function AlbumScreen({ species, discovered, imageErrors, onImageError, onHome }: { species: Species[]; discovered: string[]; imageErrors: Record<string, boolean>; onImageError: (id: string) => void; onHome: () => void }) {
return <section className="content notebook-page"><div className="section-heading"><div><span className="eyebrow">אוסף המינים</span><h1>עשרת הנחשים הראשונים</h1><p>מאגר התמונות האמיתי נפתח. לכל צילום נשמרים בעלות, תגיות ורמת קושי.</p></div><button className="ghost" onClick={onHome}>חזרה למחנה</button></div><div className="grid">{species.map((item) => { const approved = item.media.find((media) => media.approved); const visibleImage = approved && !imageErrors[item.id]; const unlocked = discovered.includes(item.id); return <article className="snake-card" key={item.id}><div className="image-wrap">{visibleImage ? <img src={approved.src} alt={approved.alt} onError={() => onImageError(item.id)} /> : <div className="image-placeholder"><span>{unlocked ? "📷" : "🔒"}</span><strong>{unlocked ? "תמונה מאומתת תתווסף כאן" : "הקלף עדיין נעול"}</strong></div>}</div>{visibleImage && unlocked && <div className="media-strip"><span>📷 {item.media.filter((media) => media.approved).length} צילומים מאומתים</span><small>© {approved.photographer}</small></div>}<div className="card-body"><div className="title-row"><div><h2>{unlocked ? item.name : "מין מסתורי"}</h2><small>{unlocked ? item.scientificName : "השלימו משלחת כדי לגלות"}</small></div><span className={`tag ${riskClass(item.status)}`}>{unlocked ? item.status : "נעול"}</span></div>{unlocked && <><p>{item.region}</p><div className="clue"><strong>רמזי זיהוי</strong><ul>{item.identificationClues.slice(0, 2).map((clue) => <li key={clue}>{clue}</li>)}</ul></div><p className="safety-note">🛡️ {item.safetyNote}</p></>}</div></article>; })}</div></section>;
}

export function SpeciesReveal({ item, pageNumber, onJournal, onClose }: { item: Species; pageNumber: number; onJournal: () => void; onClose: () => void }) {
const approved = item.media.find((media) => media.approved); return <div className="reveal-overlay" role="dialog" aria-modal="true" aria-labelledby="reveal-title"><div className="leaf-burst" aria-hidden="true">{["🍃","🌿","🍂","🍃","🌱","🍂","🌿","🍃"].map((leaf, index) => <span key={index} style={{ "--leaf-index": index } as React.CSSProperties}>{leaf}</span>)}</div><section className="reveal-panel"><span className="reveal-kicker">תגלית חדשה!</span><div className="species-reveal-card"><div className="reveal-card-face"><span className="reveal-number">עמוד {String(pageNumber).padStart(2, "0")}</span>{approved ? <img className="reveal-photo" src={approved.src} alt={approved.alt} /> : <div className="reveal-photo-placeholder">🐍</div>}<h1 id="reveal-title">{item.name}</h1><em>{item.scientificName}</em><p>{item.identificationClues[0]}</p><span className={`tag ${riskClass(item.status)}`}>{item.status}</span></div></div><p className="reveal-copy">הקלף נוסף לאוסף ועמוד חדש נפתח ביומן השדה.</p><button className="primary reveal-action" onClick={onJournal}>📖 פתח את יומן השדה</button><button className="reveal-skip" onClick={onClose}>המשך במסלול</button></section></div>;
}
