import type { Confidence, DetectivePhase, MediaAsset } from "../types/game";
import { answerClass } from "../lib/game";
import { ChallengeHeader } from "./GameUI";

type CaseView = { observationPrompt: string; observationChoices: string[]; bestObservation: number; observationFeedback: string; prompt: string; choices: string[]; correct: number; explanation: string; photo: MediaAsset };
export function InvestigationMission({ current, index, total, phase, selected, observationSelected, confidence, feedbackLine, onClose, onObservation, onPhase, onChoose, onConfidence, onNext }: { current: CaseView; index: number; total: number; phase: DetectivePhase; selected: number | null; observationSelected: number | null; confidence: Confidence | null; feedbackLine: string; onClose: () => void; onObservation: (index: number) => void; onPhase: (phase: DetectivePhase) => void; onChoose: (index: number) => void; onConfidence: (value: Confidence) => void; onNext: () => void }) {
return <section className="challenge notebook-page"><ChallengeHeader onClose={onClose} progress={((index + (phase === "observe" ? 0.25 : phase === "identify" ? 0.65 : 1)) / total) * 100} icon="🔎" /><div className="challenge-card"><span className="question-label">תיק חקירה {index + 1}/{total} · {phase === "observe" ? "מתבוננים" : phase === "identify" ? "מזהים" : "בודקים ביטחון"}</span><div className="photo-question-card detective-photo"><div className="field-photo-wrap"><img src={current.photo.src} alt={current.photo.alt} /><span className={`difficulty difficulty-${current.photo.difficulty}`}>{current.photo.difficulty === 1 ? "קל" : current.photo.difficulty === 2 ? "בינוני" : "מצב שטח"}</span>{phase !== "observe" && <span className="clue-stamp">רמז נבדק ✓</span>}</div><div className="photo-meta"><span>צילום אמיתי · © {current.photo.photographer}</span><small>{current.photo.tags.join(" · ")}</small></div></div>
{phase === "observe" && <><div className="detective-step"><span>1</span><div><strong>עוצרים לפני שמנחשים</strong><small>קודם מתארים מה רואים. רק אחר כך נותנים שם למין.</small></div></div><h1>{current.observationPrompt}</h1><div className="choice-list observation-list">{current.observationChoices.map((choice, choiceIndex) => <button key={choice} className={observationSelected === choiceIndex ? (choiceIndex === current.bestObservation ? "correct" : "selected-neutral") : ""} onClick={() => onObservation(choiceIndex)}>{choice}</button>)}</div>{observationSelected !== null && <div className={`observation-note ${observationSelected === current.bestObservation ? "sharp" : "coach"}`}><strong>{observationSelected === current.bestObservation ? "🔎 הבחנה חדה" : "🌿 כיוון טוב, אבל יש רמז אמין יותר"}</strong><p>{current.observationFeedback}</p><button className="primary" onClick={() => onPhase("identify")}>עכשיו אפשר לזהות</button></div>}</>}
{phase === "identify" && <><div className="detective-step"><span>2</span><div><strong>מחברים את הרמזים</strong><small>לא מסתמכים על צבע או סימן יחיד.</small></div></div><h1>{current.prompt}</h1><div className={`choice-list ${current.choices.length === 2 ? "two" : ""}`}>{current.choices.map((choice, choiceIndex) => <button key={choice} className={answerClass(selected, choiceIndex, current.correct)} onClick={() => onChoose(choiceIndex)}>{choice}</button>)}</div>{selected !== null && <div className={`feedback ${selected === current.correct ? "good" : "try"}`}><div className="feedback-title"><span>{selected === current.correct ? "🍃" : "🔎"}</span><strong>{selected === current.correct ? feedbackLine : "עוד רמז אחד — ותזהה בפעם הבאה."}</strong></div><p>{current.explanation}</p><button className="primary" onClick={() => onPhase("confidence")}>בדיקת ביטחון</button></div>}</>}
{phase === "confidence" && <><div className="detective-step"><span>3</span><div><strong>בלש טוב יודע גם לומר „לא בטוח”</strong><small>הדיווח הזה לא משנה את הציון — הוא עוזר ללמוד נכון.</small></div></div><h1>עד כמה היית בטוח בתשובה?</h1><div className="confidence-grid"><button className={confidence === "sure" ? "active" : ""} onClick={() => onConfidence("sure")}><span>🎯</span><strong>בטוח</strong><small>זיהיתי כמה רמזים</small></button><button className={confidence === "maybe" ? "active" : ""} onClick={() => onConfidence("maybe")}><span>🤔</span><strong>די בטוח</strong><small>היה לי רמז אחד טוב</small></button><button className={confidence === "guess" ? "active" : ""} onClick={() => onConfidence("guess")}><span>🎲</span><strong>ניחוש</strong><small>לא הצלחתי להסביר למה</small></button></div>{confidence && <div className="confidence-note"><strong>{confidence === "guess" ? "ניחוש ישר עדיף מביטחון מזויף." : confidence === "maybe" ? "מצוין. בפעם הבאה נחפש עוד רמז אחד." : "מעולה — ודא שהביטחון מבוסס על יותר מסימן אחד."}</strong><p>בשדה תמיד שומרים מרחק, גם כשמרגישים בטוחים בזיהוי.</p><button className="primary" onClick={onNext}>{index === total - 1 ? "סיום תיק החקירה" : "לתיק הבא"}</button></div>}</>}
</div></section>;
}
